### ISSUE TITLE
Change "Character Sequences" and `S#` to "Character Resonance Chain" and `RC#` for Consistency

### ISSUE THREAD

**Issue by Kagukara** [Luzefiru/wuwatracker#123]
## Problem

"Character Sequences" should be changed to "Character Resonance Chain" as seen in-game. I had no idea what "Character Sequences" was until I actually clicked onto the page.

## Possible Solution

Swap every mention of: 
- "Sequences" → "Resonance Chain"
- `S#` → `RC#`

This makes it more consistent with what the game shows and what is displayed on wuwatracker.

## Additional Context or Screenshots

In-Game: 
![capture_2024-07-25_01-43-38](https://github.com/user-attachments/assets/823dee1c-a33b-4f6f-b5e8-998c309e7682)

URL: https://wuwatracker.com/sequences

**Comment by Kagukara** [comment]
@antisocial93 Might be worth just changing the page title then, as shown in the [prydwen.gg](https://www.prydwen.gg/wuthering-waves/characters/jinhsi) image you provided.

**Comment by antisocial93** [comment]
@Kagukara You're right at some point. If you want to - you could join the discussion in our Discord, I created a topic so everyone can give self thoughts about it. Discord topic: https://discord.com/channels/1246763932203618325/1265952755558776914

**Comment by Luzefiru** [comment]
We're now using `S#` and `R#` for Resonators & Weapons, respectively in the latest update. Thanks for pointing this out @Kagukara!

## Demo
![image](https://github.com/user-attachments/assets/0df5777d-d28d-4ae7-87d4-fb34dcef4908)
![image](https://github.com/user-attachments/assets/72f20f1d-5013-4dac-8c89-79e08da466f8)
