### ISSUE TITLE
Duplication error on filtering out 4* when viewing wish history

### ISSUE THREAD

**Issue by tiffanynwyeung** [Luzefiru/wuwatracker#29]
# Bug Description
I imported my wish history into the app, and then attempted to filter out all 4* event character wishes from being viewed. However, it left one particular 4* wish in, and from repeatedly toggling the 4* filter button, it ended up duplicating that particular wish throughout the view. This goes away on hard refresh.

![wuwatrackerbug](https://github.com/Luzefiru/wuwatracker/assets/8635193/ed6811e7-244b-4543-8d24-d8ab3ada6dfe)

## How to Reproduce

1. Import wish history onto website
2. Navigate to 'History' tab to view all 4/5* wishes
3. Toggle 4* wish filter button when viewing character wishes

## Expected Behavior

_What is the expected behavior without the bug?_
I expect to filter out all 4* event character wishes, leaving only the 5* event character wishes to be displayed.

## Platform/OS
_Desktop (please complete the following information):_ Windows 10, Google Chrome (ver. 125)

**Comment by Luzefiru** [comment]
We're investigating this at the moment. Thank you for raising this issue.
