### ISSUE TITLE
Add image for sharing pull history

### ISSUE THREAD

**Issue by Renari** [Luzefiru/wuwatracker#43]
# Problem

_Is your feature request related to a problem? Please describe._
It's nice to be able to share your pull history in a concise way, this can be accomplished by taking a screenshot, but the format of the webpage does not make it easy to understand at a glance.

## Possible Solution

_Describe the solution you'd like_
Be able to generate an image to share, potentially showing current pity, how many pulls on the banner which banner this image is for etc. Maybe the possibility to show/hide 4*. 

starrrailstation has something similar to this:
![image](https://github.com/Luzefiru/wuwatracker/assets/1839179/62a9973c-1b8b-43e5-b8e5-ad98c48f5064)

**Comment by Luzefiru** [comment]
This is a nice-to-have feature and a good addition to the website. However, I'll be prioritizing global statistics & cloud sync at the moment. 😓

If someone else would like to work on a share feature like this, please let us know! 🙏

**Comment by Luzefiru** [comment]
We have this now! Check it out in the [Share History page](https://wuwatracker.com/convene/share).

**Comment by Luzefiru** [comment]
Closing this issue now as completed. You can even customize it like so:

![Thawborn Renewal (17)](https://github.com/Luzefiru/wuwatracker/assets/105530193/063df087-8de2-4b78-879c-9b4108c3a283)

We're going to be changing the layout in the future once we find a graphic designer willing to help us.

Thank you for making this suggestion!
