### ISSUE TITLE
Android Support Possible Method (No PC or Root Needed)

### ISSUE THREAD

**Issue by Luzefiru** [Luzefiru/wuwatracker#55]
# Problem

We don't have Android support, but we found a possible solution. We need confirmation from multiple users using different devices & Android version before we can highly recommend it.

## Possible Solution

> [!Warning]
> This is experimental, so use it at your own risk! We're not responsible for any damages this may cause to your device.

I got a report from one of our Discord members, `@siptik`, that an Android method for retrieving the data for Honkai Star Rail / Other Mihoyo apps works for Wuthering Waves too.

It basically reads your system logs using the Android tool [logcat](https://developer.android.com/tools/logcat) while you play the game before filtering the Convene History URL.

For the full solution, go to [wuwatracker.tech Discord Server's forum post](https://discord.com/channels/1246763932203618325/1248479838210228236).

## Additional Context or Screenshots
Here's a copy-paste version of my post on the Discord Server (as of 06/07/24):
Credits to @siptik for finding & trying this out.

> [!Note]
> **Disclaimer**: We still need more people to try it out before we officially add it as a method in our website.

Apparently, one of the method used to get the History URL in Star Rail Station's Discord can work for Wuthering Waves. If this is true, we can test the methods ourselves to see if they really work and are stable so that we can recommend it to Android users.
## Tutorial
To do this, **read this entire tutorial first**, then follow this step-by-step tutorial:
1. **FIRST**, read this written guide taken from Star Rail Station Discord, called Android Method 2: via [Ascent](https://gist.github.com/Mirai0009/8615e52e09083de9c0ea2dc00dc62ea8) or [Brevent](https://gist.github.com/Mirai0009/fa4307e97ad40e71f89754c372b3ba91)
2. Next, follow this YouTube video tutorial provided by `@miraiwangy` from the same Discord, based on the tutorial you are reading: [YouTube: IMPORT VIA BREVENT](https://www.youtube.com/watch?v=jJjvC8KiMDk) or [YouTube: IMPORT VIA ASCENT](https://www.youtube.com/watch?v=wWzucdG3b14)
3. **This part is the most important step that differs from the video/HSR tutorial**, for the [exec command at this timestamp](https://youtu.be/jJjvC8KiMDk?feature=shared&t=53), enter  `logcat -e https://aki-gm-resources-oversea.aki-game.net`
  -  use this instead if you are from the Chinese server `logcat -e https://aki-gm-resources-oversea.aki-game.com`.
### Successful End Result
If it works successfully, you will get a link that looks like this:
```
https://aki-gm-resources-oversea.aki-game.net/aki/gacha/index.html#/record?svr_id=10cd7254d57e58ae560b15d51e34b4c8&player_id=900643805&lang=en&gacha_id=100001&gacha_type=1&svr_area=global&record_id=e005b89e3a163ff66d2bbc9263b9a434&resources_id=5c13a63f85465e9fcc0f24d6efb15083
``` 
## Does it always work?
We're not sure. I'm hoping that other people can test this if it works successfully and report if they run into issues along the way.

Use this template when creating a report here after trying it out:
```md
### Method Used
- Brevent/Ascent
### Device Info
- Device Model: [e.g., Samsung Galaxy S21]
### Android Version
- Android Version: [e.g., Android 12]
### Status
Success/Fail
```

**Comment by Gol-D-Ace** [comment]
So the Termux wireless debugging adb method should also work.

**Comment by Luzefiru** [comment]
> So the Termux wireless debugging adb method should also work.

Yes! This was confirmed by another user of the website and they were kind enough to create a [GitHub Gist about it](https://gist.github.com/eqdamini/d3accb76dc5e82f9c30d398a9fc5626d).
