### ISSUE TITLE
banned for using?

### ISSUE THREAD

**Issue by PatrickYuki** [Luzefiru/wuwatracker#59]
Will a player get banned for using this 3rd party tool? is it detectable?

**Comment by Luzefiru** [comment]
It works similar to [paimon.moe](https://paimon.moe/wish) and [Star Rail Station](https://starrailstation.com/en/warp) where we get your history using their own publicly available data - in theory, it's no different than opening your in-game history logs (which is just also webpage). We do not tamper with your game in any way.

You can read the specific process of the script [in my GitHub Gist here](https://gist.github.com/Luzefiru/19c0759bea1b9e7ef480bb39303b3f6c).

> [!Warning]
> Even if there have not been any ban reports after using this tool, but please use it at your own risk.
