### ISSUE TITLE
Google Sync: No user record created with that userId

### ISSUE THREAD

**Issue by gavenda** [Luzefiru/wuwatracker#64]
# Bug Description

After signing in, cloud sync keeps blinking in red.

Also in console logs:
```
23-8785484217d6512d.js:1  Error: No user record created with that userId!
    at o (31-5c58f07b1d5434ac.js:1:4595)
    at async 31-5c58f07b1d5434ac.js:1:6469
```

Is signing in to google supposedly create some user on your end?

## How to Reproduce

1. Open site
2. Sign in with google
3. Agree to experimental feature
4. See error in console

## Expected Behavior

Data should sync without issue.

## Platform/OS

_Desktop (please complete the following information):_

- OS: [Windows 11]
- Browser [Edge]

**Comment by Luzefiru** [comment]
The red blinking indicates that you haven't pressed the Sync button. Does it turn green when you press the sync button once you are logged in?

**Comment by gavenda** [comment]
> The red blinking indicates that you haven't pressed the Sync button. Does it turn green when you press the sync button once you are logged in?
> 
> > Is signing in to google supposedly create some user on your end?
> 
> Yes, it inserts a user table row to associate your Convene History URL.

That error came up when I clicked on sync data.

Anyway I tried it again in incognito and it worked after some time.

I'll open it up again if it persists again.
