### ISSUE TITLE
Incorrect Resonator Sequences

### ISSUE THREAD

**Issue by paragkatoch** [Luzefiru/wuwatracker#66]
# Problem

There are some ways to get resonators other then convene which will not show up in tracker
1. Beginer's Choice convene (Giveback Custom Convene) (where we got a free standard 5* pull)
2. Buying through Shop using Afterglow coral

## Possible Solution

Adding a way to increase/decrease sequences of Resonators in [Sequences](https://wuwatracker.tech/sequences) like paimon.me

## Additional Context or Screenshots

<img width="1144" alt="Screenshot 2024-06-13 at 7 01 40 PM" src="https://github.com/Luzefiru/wuwatracker/assets/61873006/73644e1d-887b-4af9-8d63-ed452a1f4455">

**Comment by Ronambulo** [comment]
I thought the same thing

**Comment by Luzefiru** [comment]
We are currently implementing a manual input feature for this. We'll let y'all know when it's ready!

**Comment by Luzefiru** [comment]
You can now manually edit your sequences in the [Sequences Page](https://wuwatracker.com/sequences)!

One limitation at the moment is that it doesn't sync with your Google Account, but it does save with your web browser's local storage.

Please let us know if it works well on your ends, @paragkatoch, @Ronambulo. ✨

**Comment by paragkatoch** [comment]
Yeah, it works on my side

**Comment by Luzefiru** [comment]
Alright, I'm closing this issue now. Kindly open another issue if you find a bug or want to suggest something related to it. Thanks @paragkatoch!
