### ISSUE TITLE
Timezone in Timeline

### ISSUE THREAD

**Issue by paragkatoch** [Luzefiru/wuwatracker#68]
# Problem
The time in [Timeline](https://wuwatracker.com/timeline) is without timezone. Thus leading to confusion.

<img width="1385" alt="Screenshot 2024-06-26 at 10 09 54 AM" src="https://github.com/Luzefiru/wuwatracker/assets/61873006/8fb22f59-6fab-4966-bdf1-e56ee1e916d7">

## Possible Solution

Really like the idea of crowdsourcing the event updates, but we can add a rule to it that the time should be in [server time](https://esports.gg/guides/gaming/server-time-wuthering-waves-timezones/) i.e., UTC+8  and then we can convert it to the user's timezone on client side.

**Comment by Luzefiru** [comment]
Currently, the data is indeed using the server time (UTC+8) based on the in-game announcements from SEA and their [official website](https://wutheringwaves.gg/wuthering-waves-version-1-1-update-maintenance-notice/) notices. But ideally, I'd want to make it much easier for the user to update the site data without having to do the conversions themselves.

To combat this in the meantime, I added a comment beside the type definition to use the server time, but there has to be a better way to do it.

```ts
export interface Event {
  id?: number; // announcement id
  name: string;
  description?: string;
  img: string;
  startDate: string; // use Server time (UTC+8)
  endDate: string; // use Server time (UTC+8)
  color?: string; // defaults to automatically detecting the img color (prefer darker colors)
  url?: string; // link to an informative page about the event
  showOnHome?: boolean; // whether we show it in the home dashboard
}
```

Thanks for raising this issue!

**Comment by Luzefiru** [comment]
Hiya @paragkatoch, the website has been updated to automatically detect the user's local time zone. It also has the options to pick which game server time you'd like to view as.

To keep it accurate, we still have to encode the data here as CST (UTC+8) `YYYY-MM-DD HH:mm` strings. What do you think?

![test](https://github.com/Luzefiru/wuwatracker/assets/105530193/f62f6507-d2b4-4d78-9113-3013ed90b54e)

**Comment by paragkatoch** [comment]
@Luzefiru The implementation is really good, but I think the conversion is not working as expected for events.

For featured banners
1. The start time will be different based on regions (13:00 CST, 10:30 IST, 5:00 UTC)
2. The 'start in' timer should be same for all regions. (since they globally launch at the same time)

I think some events start globally at the same time and other start based on their regional time. Same can be said for end time as well. Need to monitor the start/end time for future events to verify this.

A flag might be needed if the above is true.

https://github.com/Luzefiru/wuwatracker/assets/61873006/b8407b6e-06a4-4b15-be40-74eb84f742f0

**Comment by Luzefiru** [comment]
> I think some events start globally at the same time and other start based on their regional time. Same can be said for end time as well. Need to monitor the start/end time for future events to verify this.

Yeah, this is the case for Genshin. I'm doing my best to look into a proper way to do this at the moment.

**Comment by paragkatoch** [comment]
Time and timer is working perfectly for my region. But, if I switch to other region then they are wrong.

Like for Chicago its around 23:30 on 27th but it is showing 28th

<img width="1072" alt="Screenshot 2024-06-27 at 2 46 16 PM" src="https://github.com/Luzefiru/wuwatracker/assets/61873006/389e7634-7892-4ed9-9e85-539675c97a80">

**Comment by Luzefiru** [comment]
Okay, I think I found the issue, can I reach you out via Discord? I'd appreciate it if you could make some time to test it out.

**Comment by paragkatoch** [comment]
Sure, joined the discord channel

**Comment by antisocial93** [comment]
![image](https://github.com/Luzefiru/wuwatracker/assets/174001750/00fd38d9-74a2-4a67-b6b4-e326d838ce46)
It seems to be perfect now, exactly when server resets at UTC+3

**Comment by antisocial93** [comment]
I assume there is no need in this list anymore?
![image](https://github.com/Luzefiru/wuwatracker/assets/174001750/b11801ff-dda9-415e-ab97-610c15a09258)
Because its change ruining everything
![image](https://github.com/Luzefiru/wuwatracker/assets/174001750/5fa5404e-dddc-4484-aa0e-69b44db0f04b)

**Comment by Luzefiru** [comment]
> Because its change ruining everything
The next update to the site should fix this. Please let me know if you're having any issues despite that, @antisocial93.

**Comment by antisocial93** [comment]
> > Because its change ruining everything
> > The next update to the site should fix this. Please let me know if you're having any issues despite that, @antisocial93.

There is one, btw
The hazard zone, which info about i'd commited today to events.ts stopped showing itself in the timeline
![image](https://github.com/Luzefiru/wuwatracker/assets/174001750/96b6a06e-cf7e-4314-bb84-a16d57817fa1)
![image](https://github.com/Luzefiru/wuwatracker/assets/174001750/5794d2f6-369a-4a76-a892-2352af616c3f)

**Comment by Luzefiru** [comment]
Is this issue still open, @paragkatoch?
