### ISSUE TITLE
Starting time on Changli Banners doesn't match starting time on Banner

### ISSUE THREAD

**Issue by foopod** [Luzefiru/wuwatracker#70]
# Bug Description

In the dialogue that opens when you click an event, the The lower white "starting in.." says "Starting in 1mo 21d XX:XX:XX", but it shouldn't have 1mo in this string (only shows on the Changli banners).

## How to Reproduce

1. Go to 'https://wuwatracker.com/timeline'
2. Click on 'Stellar Plummage' Event
3. See error

## Expected Behavior

It should show the accurate number of months + days + hours + minutes + seconds. For this banner it should be "Starting in 21d XX:XX:XX".

## Screenshots

![image](https://github.com/Luzefiru/wuwatracker/assets/3768616/15f2ab54-c787-4e36-ba2f-e11bee64a41c)

## Platform/OS

- OS: Arch Linux (Kernel: 6.6.31-2-lts)
- Browser: Firefox
- Version: 126.0

## Additional Context

This doesn't look like a data issue and is probably down to how this is calculated.

## Would I like to work on this? 

Sure. But I don't see any code in here, just data + assets.

**Comment by Luzefiru** [comment]
Ah, this is probably because I used the banner's end time as the value for the banner's start value. I'll be fixing this ASAP. Thanks for raising the issue!

**Comment by Luzefiru** [comment]
Alright, I've pushed some changes. Is the issue resolved on your end, @foopod?

**Comment by foopod** [comment]
@Luzefiru lgtm

**Comment by Luzefiru** [comment]
> @Luzefiru lgtm

Cool. I'll be closing this issue then. Feel free to raise another issue if you find any! 👍
