### ISSUE TITLE
Timeline:- Stacking events row-wise to reduce vertical space

### ISSUE THREAD

**Issue by paragkatoch** [Luzefiru/wuwatracker#82]
# Problem

 Right now every new event is creating its separate row in timeline, because of which timeline gets really long vertically.

<img width="1440" alt="Screenshot 2024-07-02 at 7 42 49 PM" src="https://github.com/Luzefiru/wuwatracker/assets/61873006/bfa4532d-c66a-4a1b-8de6-fb524c57d7ea">

## Possible Solution

I can think of two solutions

1. Automatically stacking the events to empty rows (this might make is look chaotic)
2. Assigning different rows for different kinds of events. Assign -
a) 2 rows for banners (resonator + weapon)
b) 1 row for Pioneer Podcast
c) 1 row for Tower of Adversity
d) 10 rows (safe number) for long events
e) 10 rows (safe number) for short events

Additionally, apply stacking separately to these groups.
Although all this might depend on the library.

## Example 

<img width="1178" alt="Screenshot 2024-07-02 at 8 15 23 PM" src="https://github.com/Luzefiru/wuwatracker/assets/61873006/7caaca14-5863-439a-9371-5ceca2ba88f0">

**Comment by Luzefiru** [comment]
Heya, @paragkatoch! Thank you so much for the suggestion. We finally implemented this! Instead of hard-coding rows, I added a `group` property to the `Event` interface. The code will automatically sort by ascending group number first, then ungrouped events.

```diff
export interface Event {
  id?: number; // announcement id
  name: string;
  description?: string;
  img: string;
  startDate: string; // use Server time (UTC+8)
  endDate: string; // use Server time (UTC+8)
  color?: string; // defaults to automatically detecting the img color (prefer darker colors)
  url?: string; // link to an informative page about the event, always prefer https://wutheringwaves.kurogames.com/en/main/news
  showOnHome?: boolean; // whether we show it in the home dashboard
  isGlobal?: boolean;
  sourceName?: string; // the display name of the source URL
  reliability?: 'Leak' | 'Official';
+  group?: number; // events with the same group will overlap and merge if they are within 1 hour from each other's start & end dates, respectively
}

+ export const EVENT_GROUP = {
+  PIONEER_PODCAST: 0,
+  ILLUSIVE_REALM: 1,
+  TOWER_OF_ADVERSITY: 2,
+  DOUBLE_DROPS: 3,
+};
```

```diff
{
      name: 'Pioneer Podcast',
      img: 'https://snipboard.io/dBPpt2.jpg',
      color: '#e4c190',
      description: `You can complete tasks in Pioneer Podcast and accumulate Podcast EXP. Level up your Podcast to get rich rewards. Unlock "Insider Channel" or "Connoisseur Channel" and level up your Podcast to win extra rewards including Astrite*600, a 4-star Golden Eternal Series Weapon of Choice, and Radiant Tide!`,
      startDate: '2024-06-28 12:00',
      endDate: '2024-08-13 03:59',
      isGlobal: true,
      url: 'https://wutheringwaves.kurogames.com/en/main/news/detail/975',
      reliability: 'Official',
+     group: EVENT_GROUP.PIONEER_PODCAST,
},
```

![image](https://github.com/user-attachments/assets/35dc2624-9098-449a-90be-8fd3373e54f4)


At the moment, events will "merge" together in the same row if the previous event's end time is within 1 hour before the next event's start time. Would you say this is a good approach?

**Comment by paragkatoch** [comment]
Yeah, seems good
